# Compilador y banderas
CC = gcc
CFLAGS = -Wall -Wextra -std=c99 -Iinclude  # Añadimos -Iinclude para incluir la carpeta include

# Archivos fuente (ahora se encuentran en la carpeta src)
SRC = src/main.c src/funciones.c src/txt_reader.c

# Archivos objeto (con la misma ruta de la carpeta src)
OBJETOS = $(SRC:.c=.o)

# Nombre del ejecutable
EJECUTABLE = tarea1

# Regla principal
all: $(EJECUTABLE)

# Cómo construir el ejecutable
$(EJECUTABLE): $(OBJETOS)
	$(CC) $(CFLAGS) -o $@ $^

# Regla para compilar archivos .c a .o
src/%.o: src/%.c
	$(CC) $(CFLAGS) -c $< -o $@

# Limpiar archivos generados
clean:
	del *.o $(EJECUTABLE)